import React from "react";
import withStyles from "@material-ui/core/styles/withStyles";
import Table from "@material-ui/core/Table";
import TableBody from "@material-ui/core/TableBody";
import TableCell from "@material-ui/core/TableCell";
import Link from "react-router-dom/Link";

// import TableContainer from "@material-ui/core/TableContainer";
import TableHead from "@material-ui/core/TableHead";
import TableRow from "@material-ui/core/TableRow";

import { getAllCertificates } from "../Utils/apiConnect";

const styles = (theme) => ({
  root: {
    minHeight: "91.5vh",
  },

  textitems: {
    margin: "20px 10px",
    textAlign: "center",
  },
});

class AllCertificates extends React.Component {
  state = {
    certifcates: [],
    CompanyName: "UIET",
  };

  componentDidMount() {
    getAllCertificates().then((data) => {
      console.log("yay!", data);
      data.forEach((element) => {
        element.assignDate = new Date(element.assignDate)
          .toString()
          .slice(4, 15);
        element.expirationDate = new Date(element.expirationDate)
          .toString()
          .slice(4, 15);
      });
      this.setState((prev) => {
        const temp = prev;
        temp.certifcates = data;

        return temp;
      });
    });
  }

  render() {
    return (
      <div className="container">
        <h1>{`Certificates generated by ${this.state.CompanyName} are:`}</h1>
        <Table sx={{ minWidth: 650 }} aria-label="simple table">
          <TableHead>
            <TableRow style={{ fontWeight: "bolder" }}>
              <TableCell>Name</TableCell>
              <TableCell>Organisation</TableCell>
              <TableCell>Course</TableCell>
              <TableCell align="right">Link</TableCell>
              <TableCell align="right">Assign Date</TableCell>
              <TableCell align="right">Expiration Date</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {this.state.certifcates.map((row) => (
              <TableRow
                key={row.candidateName}
                sx={{ "&:last-child td, &:last-child th": { border: 0 } }}
              >
                <TableCell
                  component="th"
                  scope="row"
                  style={{ fontWeight: "bold" }}
                >
                  {row.candidateName}
                </TableCell>

                <TableCell align="left">{row.orgName}</TableCell>
                <TableCell align="left">{row.courseName}</TableCell>
                <TableCell
                  scope="row"
                  component={Link}
                  to={`/display/certificate/${row.certificateId}`}
                  align="right"
                  style={{ color: "blue" }}
                >
                  view
                </TableCell>
                <TableCell align="right">{row.assignDate}</TableCell>
                <TableCell align="right">{row.expirationDate}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    );
  }
}

export default withStyles(styles)(AllCertificates);
